### ISSUE TITLE
some small (mostly indiewebby) things to fix on the site

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/website#14]
- [ ] make integrated Twitter feed actually show our tweets
- [ ] redirect to https when they hit http
- [x] start POSSE blogging
- [ ] add some microformats markup
- [ ] display webmentions, including bridgy ones
- [ ] see what else from indiewebify.me/indiemark we can apply

**Comment by pierreozoux** [comment]
I'll close this in favor of a new issue (use known ) :)
