### ISSUE TITLE
document partial migration options

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/website#24]
For full migration, it is necessary that at least two hosters offer a full product, including all its various features (e.g TLS, CMS, etc.). In practice, people will often do a partial migration, and either leave the rest behind, or switch to something the new hoster provides.

Even for one application, there may be more than one way to migrate. For instance when you switch email providers, you typically don't migrate over the mailboxes. For your CMS you may also move just the posts over, and not all the configuration settings.

For each feature, we should list in detail how and from where the data for this feature can be imported, and how and to where it can be exported.

**Comment by pierreozoux** [comment]
I think that now the definition of an IndieHosters is somebody that embrace the infra as well, so this wouldn't apply anymore.
