### ISSUE TITLE
URI #fragments for sections

### ISSUE THREAD

**Issue by elf-pavlik** [indiehosters/website#26]
currently many sections doesn't allow linking directly to them, for example:
/#software could link to *Applications we will offer* section which people might like to share with friends

**Comment by pierreozoux** [comment]
I checked, it should be better now.
I updated the website to have a pay button, and many other things.
I let you close the issue if you believe it's good enough?

But there is still some work to do :) But features are there!

**Comment by elf-pavlik** [comment]
https://indiehosters.net/index.html#applications cool, thx!
