### ISSUE TITLE
Link in the newsletter website

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/website#33]
Hey @michielbdejong, cn you please remove the link from the confirmation email:
 https://subscribe.indiehosters.net/

This link points to a blank wordpress, it would be nicer to point to our website.

Danke!

**Comment by michielbdejong** [comment]
Are we sending out confirmation emails? That surprises me.

**Comment by pierreozoux** [comment]
I guess, it's a user that reported me that.

Or maybe it's the confirmation page?

**Comment by michielbdejong** [comment]
I just signed up and could not reproduce the problem:

![newsletter-confirm](https://cloud.githubusercontent.com/assets/408412/5801772/ff20aaa2-9fee-11e4-8387-c47ebc16474b.png)

**Comment by michielbdejong** [comment]
Ah, found the problem. It's not the confirmation email, but the welcome email:

https://subscribe.indiehosters.net/wp-admin/admin.php?page=newsletter_subscription_options

**Comment by michielbdejong** [comment]
fixed.

**Comment by pierreozoux** [comment]
Cool!
