### ISSUE TITLE
Add a demo button for each application

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/website#37]
@michielbdejong 
What do you think of having a demo for each application we host?
We have to split who is hosting what.
Do you have a wildcard cert for IndieHosters.net?

**Comment by michielbdejong** [comment]
Yes, good idea! I don't have a wildcard cert, no, but we can just get 7 certs for just known, wordpress, owncloud, trovebox, piwik, ghost, and cozy.

**Comment by michielbdejong** [comment]
Although once you have time again, you will also switch to "indiehosters stage 2", right? So then we can do a website update saying we now host any personal server applications, and here are some examples. It would then also make more sense to distinguish "what will you use your personal server for? and then split into:

* "running my personal website" (known/wordpress/ghost/whatever you like)
* "personal files" (owncloud/cozy/whatever you like) 
* "multi-purpose" (sandstorm/yunohost)
* "special-purpose" (gitlab/trovebox/mediagoblin).

Would you then still display demo buttons for all those examples? Maybe just say your IndieHoster will advise you and talk you through these choices?

**Comment by michielbdejong** [comment]
I also thought, in this context (maybe come to irc, so we can discuss this online), that it might make more sense longer-term to have one sign-up flow based on these questions, and then decide who will host you automatically, based on your requirements, and on hoster specialization. It would become a bit like a marketplace for sales leads. This would require some web development, but maybe we should find a way to do get that done.

**Comment by pierreozoux** [comment]
One cert per application is a bit overkilling... I can host them under tokoloho.co but it is confusing to see another subdomain...

What if I buy another domain, like `indiehosters.website` and I put a wildcard there?

I'll switch to IndieHosters stage 2, when I finished freelance, I have a webmail, and socket activation.

Your proposition of split is cool, this is the idea of the `product category`, it means, we would need to add "multi-purpose" and "special-purpose"
And yes, I think the demo button is important, I love demo buttons on sites ;) and also, we should keep a page with all applicaitons for SEO purpose.
But we also advise and help the use if he needs to.

About the sign-up flow, it would be lovely! We could also detect the language of the user from the browser :) But this is a long term goal IMHO, as we need this to be implemented on our server also.

(If you answer, please split into various issues, this is confusing like this.)

**Comment by michielbdejong** [comment]
ok. purely about the demo instances - why is one cert per application overkill? I would prefer to have one wordpress-demo.indiehosters.net, trovebox-demo.indiehosters.net, etc. I don't see the need to spend money on a wildcard cert, and don't see how another domain helps? Shall I try to forward hostmaster@indiehosters.net to contact@indiehosters.net on namecheap? Then we can get all the startssl certs we need.

**Comment by pierreozoux** [comment]
I have the right to create wildcard certs for my domains :) Actually, you could say I'm the registrant, then forward hostmaster to contact, and then I can generate a wildcard \o/

**Comment by michielbdejong** [comment]
Which domains are we talking about now? It turned out hostmaster@indiehosters.net was already forwarded to contact@indiehosters.net email. I added catch-all, so now we can both get *@indiehosters.net email.

I also added a CNAME *.indiehosters.net -> k1.pierre.indiehosters.net. So you now should be able to set up the demo instances, regardless of whether you use normal certs or one wildcard one, right? Or do you need to be registrant?

**Comment by pierreozoux** [comment]
regarding rules on StartSSL, I think I have to be registrant, isn't it?
I'll work on the demo instances.
For now, we have 7 applications we can demo.

What do you think of splitting like this:
- Pierre
 - wordpress
 - known
 - piwik
-Michiel
 - Owncloud
 - ghost

static: link to IndieHsoters.net :)
mail: link to send us an email, I'll have to do email hosting for IndieHosters then :)

If you want to add applications, please, add the details about them.

**Comment by pierreozoux** [comment]
And we'll have to add reset function also, but it could be in a other iteration.
Also, we have to be careful to always host the latest version! If not, most of them show an alert to update, which is not really nice to demo :/

**Comment by michielbdejong** [comment]
OK, I'll set up https://owncloud-demo.indiehosters.net/ and https://ghost-demo.indiehosters.net/. User/pwd: test/test.
I would not list static as it's a poweruser product. But I will add https://trovebox-demo.indiehosters.net/.
For email, it's not an application, so unless you want to demo roundcube (which you don't offer, right?), I don't think there is anything to demo for that?

**Comment by michielbdejong** [comment]
In the text, I would make it clear to say "these are *some* of the applications you can ask us for, once you have signed up".

I already offer reset, it's just rm -rf, and restart the container. Or what do you mean?
