### ISSUE TITLE
example case studies

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/website#40]
About zerotier, but it could apply to us:

```
I would love some example case studies to see -
what is possible, how someone has benefited that I might identify with.
```

**Comment by elimisteve** [comment]
Ask me in a month and I'll be happy to say what I like about IndieHosters, including which services I chose to have handled by my IndieHoster and why (versus my own server, versus self-hosted, versus using a 3rd party service, etc)!

**Comment by pierreozoux** [comment]
thanks :)

**Comment by pierreozoux** [comment]
From a user:

 - mettre des exemples dans la page des service level avec des titres parlant (du genre "partage d'idées" : un blog en hébergement partagé : 25€ ou une page avec des cas (réel ou fictifs) d'utilisation et leurs tarifs
  - sur la première page, tu pourrais rediriger vers ces exemples pour tes catégories "publiez", "stoquez" et "communiquez" plutot que de rediriger direct vers la boutique.
  - tu pourrais mettre un forfait de base pour les hébergements privés (ex : 25€ sans application) et managés (ex : 100€ avec une application) pour le nom de domaine, l'espace disque, les backups et le support,
  - permettre une redirection ou deux de mail gratuite pour tous les abonements. Tant pis si ça redirige vers du gmail, l'essentiel à mon sens, c'est que le client (ou l'utilisateur) prenne consience qu'il a sa propre "maison" sur internet avec son / ses site(s) et son adresse mail !
  - préciser ce que c'est le token time, je suppose que c'est des petites taches de communication ou de documentation. Un exemple ou deux ne serait pas superflux.


@elimisteve I'm not forgetting you :) I'll soon contact you!
