### ISSUE TITLE
Add a migration network page

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/website#50]
1st: the IndieHosters network, you have to use the same infra to be part.
Like this when a user is migrating from one hoster to another, it is exactly the same for the end user
.
2nd: the migration network. You are compatible with our migration format, and we can transfer users between us :)

List as Migration network:
- portknox.net

**Comment by pierreozoux** [comment]
1st: the IndieHosters network, you have to use the same infra to be part.
Like this when a user is migrating from one hoster to another, it is exactly the same for the end user
.
2nd: the migration network. You are compatible with our migration format, and we can transfer users between us :)

**Comment by Gomez** [comment]
Count me in! Unfortunately i am still in the process of cleaning up and migrate to docker. But i am follow you guys and catching up!

**Comment by pierreozoux** [comment]
Moved to:
https://git.indie.host/meta/website/issues/23
