### ISSUE TITLE
remoteStorage entry

### ISSUE THREAD

**Issue by skddc** [indiehosters/website#59]
Is the [RS entry](https://indiehosters.net/shop/product/remotestorage-38) up-to-date? I see that the price changed, but it says:

>  It is not yet packaged for IndieHosters, but it will arrive soon! You can already order, and we'll let you know when it would be ready.

However, the package seems to be finished.

**Comment by pierreozoux** [comment]
Yes, sorry, I updated the price and the description.
What do you think?

**Comment by skddc** [comment]
Great! I think it should mention (and link) which one it is, in this case php-remote-storage. People might contribute other RS servers in the future, e.g. mysteryshack or reStore.

**Comment by skddc** [comment]
Oh by the way, would be fantastic if you could announce it on the RS forums as well:

https://community.remotestorage.io/c/integrations

**Comment by pierreozoux** [comment]
@skddc about the php, yeah, we should add it in the description. (We still have some work to better describe the products)
And good idea for the forum :) https://community.remotestorage.io/t/rs-on-indiehosters/325
