### ISSUE TITLE
Add new site HTML to this repo

### ISSUE THREAD

**Issue by elimisteve** [indiehosters/website#63]

**Comment by pierreozoux** [comment]
This would be indeed a nice to have :)
But we use a CMS (in this case odoo) so it is not easy :/
I really would like to have an edit button https://github.com/indiehosters/website/issues/49
But I have no idea how to do with odoo.

One way of doing that would be to write content on github and then copy it to odoo.
But maybe in the future, we'll go back to static website. We are thinking...
cc @pbouda

**Comment by pierreozoux** [comment]
the site has been transferred here:
https://git.indie.host/meta/website
