### ISSUE TITLE
New static website

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/website#66]
Ok, let's discuss about our new website! (I'm already all excited!)
## Problem space

It has to have the following features:
- [ ] i18n with transifex
- [ ] static
- [ ] [easily editable](https://github.com/indiehosters/website/issues/49)
## The solution space

Here are some possible solutions:
- https://github.com/Kloadut/Simone (it'll probably not be much maintained)
- jekyll of course (I have some experience with it)
- caddy (it could be nice to try a new webserver :) )

This new website has to solve:
- #49
- Landing page:
  - [ ] #40
  - [ ] #51
  - [ ] #57
- Pages/Menu
  - [ ] #28
  - [ ] #50
  - [ ] License page #54 
  - [ ] #56
  - [ ] #61 
  - [ ] #62
  - For Geek page
  - #60  
- #53

It will have the same menu as right now pointing to the other apps.

We can already write down the markdown for every new pages.

**Comment by pbouda** [comment]
Nice list. let's do it :-)

Why transifex? I am not expert in translation systems, but [weblate](https://weblate.org) looks lie a decent, free alternative. We could even host it.

For static generators I would add pelican to the list, I used it for several websites, it has nice plugins and is easy to extend. For me it would be either Jekyll or pelican. I would choose a very popular system.

**Comment by pierreozoux** [comment]
Ok, let's try weblate :)
We could even try their free plan for open source to try it out.
Just we have to be sure that the formats used are equivalent so we can
switch from one to the otehr easily (but looks like weblate is good enough)

About static, what about https://hexo.io/
Then we are going toward javascript :)
(looks like it would be easier for i18n than jekyll, I don't know
Pelican on that)

On 10-01-2016 11:24, Peter Bouda wrote:
> Nice list. let's do it :-)
> 
> Why transifex? I am not expert in translation systems, but [weblate](https://weblate.org) looks lie a decent, free alternative. We could even host it.
> 
> For static generators I would add pelican to the list, I used it for several websites, it has nice plugins and is easy to extend. For me it would be either Jekyll or pelican. I would choose a very popular system.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/indiehosters/website/issues/66#issuecomment-170336352
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by pierreozoux** [comment]
The site is now deployed :)
