### ISSUE TITLE
Set up static website for https://indie.host

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/website#69]
https://indie.host/freedom

[Basic](https://shop.indie.host/index.php?_url=/order/basic-plan)
[Personal](https://shop.indie.host/index.php?_url=/order/personal-plan)
Business

**Comment by pierreozoux** [comment]
And here is the source code:
https://t.co/HoGRqVEVMY

**Comment by elimisteve** [comment]
@pierreozoux New site looks great!
